# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/bd/msys/ip/msys_i2s_receiver_0_0_4/msys_i2s_receiver_0_0.xci
# IP: The module: 'msys_i2s_receiver_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_i2s_receiver_0_0_4/msys_i2s_receiver_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'msys_i2s_receiver_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_i2s_receiver_0_0_4/msys_i2s_receiver_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'msys_i2s_receiver_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/bd/msys/ip/msys_i2s_receiver_0_0_4/msys_i2s_receiver_0_0.xci
# IP: The module: 'msys_i2s_receiver_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_i2s_receiver_0_0_4/msys_i2s_receiver_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'msys_i2s_receiver_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_i2s_receiver_0_0_4/msys_i2s_receiver_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'msys_i2s_receiver_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
