#ifndef XPARAMETERS_H   /* prevent circular inclusions */
#define XPARAMETERS_H   /* by using protection macros */

#define XPAR_XIIC_NUM_INSTANCES 1

/* Definitions for peripheral AXI_IIC_0 */
#define XPAR_AXI_IIC_0_COMPATIBLE xlnx,axi-iic-2.1
#define XPAR_AXI_IIC_0_BASEADDR 0x40800000
#define XPAR_AXI_IIC_0_HIGHADDR 0x40803fff
#define XPAR_AXI_IIC_0_HAS10BITADDR 0x0
#define XPAR_AXI_IIC_0_GPOUTWIDTH 0x0
#define XPAR_AXI_IIC_0_INTERRUPTS 0x2003
#define XPAR_AXI_IIC_0_INTERRUPT_PARENT 0x41200001

/* Canonical definitions for peripheral AXI_IIC_0 */
#define XPAR_XIIC_0_BASEADDR 0x40800000
#define XPAR_XIIC_0_GPOUTWIDTH 0x0
#define XPAR_XIIC_0_HIGHADDR 0x40803fff
#define XPAR_XIIC_0_HAS10BITADDR 0x0
#define XPAR_XIIC_0_COMPATIBLE xlnx,axi-iic-2.1
#define XPAR_XIIC_0_INTERRUPTS 0x2003
#define XPAR_XIIC_0_INTERRUPT_PARENT 0x41200001

#define XPAR_XINTC_NUM_INSTANCES 1

/* Definitions for peripheral MICROBLAZE_0_AXI_INTC */
#define XPAR_MICROBLAZE_0_AXI_INTC_COMPATIBLE xlnx,axi-intc-4.1
#define XPAR_MICROBLAZE_0_AXI_INTC_BASEADDR 0x41200000
#define XPAR_MICROBLAZE_0_AXI_INTC_HIGHADDR 0x41203fff
#define XPAR_MICROBLAZE_0_AXI_INTC_KIND_OF_INTR 0x15
#define XPAR_MICROBLAZE_0_AXI_INTC_IS_FAST 0x1
#define XPAR_MICROBLAZE_0_AXI_INTC_IVAR_RST_VAL 0x10
#define XPAR_MICROBLAZE_0_AXI_INTC_NUM_INTR_INPUTS 0x6
#define XPAR_MICROBLAZE_0_AXI_INTC_ADDR_WIDTH 0x20
#define XPAR_MICROBLAZE_0_AXI_INTC_OPTIONS 0x0
#define XPAR_MICROBLAZE_0_AXI_INTC_INTCTYPE 0x0
#define XPAR_MICROBLAZE_0_AXI_INTC_HANDLER_TABLE 0x0

/* Canonical definitions for peripheral MICROBLAZE_0_AXI_INTC */
#define XPAR_XINTC_0_BASEADDR 0x41200000
#define XPAR_XINTC_0_HIGHADDR 0x41203fff
#define XPAR_XINTC_0_HANDLER_TABLE 0x0
#define XPAR_XINTC_0_ADDR_WIDTH 0x20
#define XPAR_XINTC_0_COMPATIBLE xlnx,axi-intc-4.1
#define XPAR_XINTC_0_IS_FAST 0x1
#define XPAR_XINTC_0_IVAR_RST_VAL 0x10
#define XPAR_XINTC_0_INTCTYPE 0x0
#define XPAR_XINTC_0_KIND_OF_INTR 0x15
#define XPAR_XINTC_0_NUM_INTR_INPUTS 0x6
#define XPAR_XINTC_0_OPTIONS 0x0

#define XPAR_XSPI_NUM_INSTANCES 2

/* Definitions for peripheral AXI_QUAD_SPI_0 */
#define XPAR_AXI_QUAD_SPI_0_COMPATIBLE xlnx,axi-quad-spi-3.2
#define XPAR_AXI_QUAD_SPI_0_BASEADDR 0x44a00000
#define XPAR_AXI_QUAD_SPI_0_HIGHADDR 0x44a03fff
#define XPAR_AXI_QUAD_SPI_0_HASFIFOS 0x1
#define XPAR_AXI_QUAD_SPI_0_SLAVEONLY 0x0
#define XPAR_AXI_QUAD_SPI_0_NUM_SS_BITS 0x1
#define XPAR_AXI_QUAD_SPI_0_BITS_PER_WORD 0x8
#define XPAR_AXI_QUAD_SPI_0_SPI_MODE 0x2
#define XPAR_AXI_QUAD_SPI_0_AXI_INTERFACE 0x0
#define XPAR_AXI_QUAD_SPI_0_AXI4_ADDRESS 0x0
#define XPAR_AXI_QUAD_SPI_0_XIP_MODE 0x0
#define XPAR_AXI_QUAD_SPI_0_STARTUP_BLOCK 0x1
#define XPAR_AXI_QUAD_SPI_0_FIFO_SIZE 0x100
#define XPAR_AXI_QUAD_SPI_0_INTERRUPTS 0x2
#define XPAR_AXI_QUAD_SPI_0_INTERRUPT_PARENT 0x41200001

/* Canonical definitions for peripheral AXI_QUAD_SPI_0 */
#define XPAR_XSPI_0_AXI4_ADDRESS 0x0
#define XPAR_XSPI_0_BASEADDR 0x44a00000
#define XPAR_XSPI_0_HIGHADDR 0x44a03fff
#define XPAR_XSPI_0_AXI_INTERFACE 0x0
#define XPAR_XSPI_0_BITS_PER_WORD 0x8
#define XPAR_XSPI_0_COMPATIBLE xlnx,axi-quad-spi-3.2
#define XPAR_XSPI_0_FIFO_SIZE 0x100
#define XPAR_XSPI_0_HASFIFOS 0x1
#define XPAR_XSPI_0_INTERRUPTS 0x2
#define XPAR_XSPI_0_INTERRUPT_PARENT 0x41200001
#define XPAR_XSPI_0_NUM_SS_BITS 0x1
#define XPAR_XSPI_0_SLAVEONLY 0x0
#define XPAR_XSPI_0_SPI_MODE 0x2
#define XPAR_XSPI_0_STARTUP_BLOCK 0x1
#define XPAR_XSPI_0_XIP_MODE 0x0

/* Definitions for peripheral AXI_QUAD_SPI_1 */
#define XPAR_AXI_QUAD_SPI_1_COMPATIBLE xlnx,axi-quad-spi-3.2
#define XPAR_AXI_QUAD_SPI_1_BASEADDR 0x44a10000
#define XPAR_AXI_QUAD_SPI_1_HIGHADDR 0x44a13fff
#define XPAR_AXI_QUAD_SPI_1_HASFIFOS 0x1
#define XPAR_AXI_QUAD_SPI_1_SLAVEONLY 0x0
#define XPAR_AXI_QUAD_SPI_1_NUM_SS_BITS 0x1
#define XPAR_AXI_QUAD_SPI_1_BITS_PER_WORD 0x20
#define XPAR_AXI_QUAD_SPI_1_SPI_MODE 0x0
#define XPAR_AXI_QUAD_SPI_1_AXI_INTERFACE 0x0
#define XPAR_AXI_QUAD_SPI_1_AXI4_ADDRESS 0x0
#define XPAR_AXI_QUAD_SPI_1_XIP_MODE 0x0
#define XPAR_AXI_QUAD_SPI_1_STARTUP_BLOCK 0x0
#define XPAR_AXI_QUAD_SPI_1_FIFO_SIZE 0x100
#define XPAR_AXI_QUAD_SPI_1_INTERRUPTS 0x4
#define XPAR_AXI_QUAD_SPI_1_INTERRUPT_PARENT 0x41200001

/* Canonical definitions for peripheral AXI_QUAD_SPI_1 */
#define XPAR_XSPI_1_AXI4_ADDRESS 0x0
#define XPAR_XSPI_1_BASEADDR 0x44a10000
#define XPAR_XSPI_1_HIGHADDR 0x44a13fff
#define XPAR_XSPI_1_AXI_INTERFACE 0x0
#define XPAR_XSPI_1_BITS_PER_WORD 0x20
#define XPAR_XSPI_1_COMPATIBLE xlnx,axi-quad-spi-3.2
#define XPAR_XSPI_1_FIFO_SIZE 0x100
#define XPAR_XSPI_1_HASFIFOS 0x1
#define XPAR_XSPI_1_INTERRUPTS 0x4
#define XPAR_XSPI_1_INTERRUPT_PARENT 0x41200001
#define XPAR_XSPI_1_NUM_SS_BITS 0x1
#define XPAR_XSPI_1_SLAVEONLY 0x0
#define XPAR_XSPI_1_SPI_MODE 0x0
#define XPAR_XSPI_1_STARTUP_BLOCK 0x0
#define XPAR_XSPI_1_XIP_MODE 0x0

#define XPAR_XTMRCTR_NUM_INSTANCES 1

/* Definitions for peripheral AXI_TIMER_0 */
#define XPAR_AXI_TIMER_0_COMPATIBLE xlnx,axi-timer-2.0
#define XPAR_AXI_TIMER_0_BASEADDR 0x41c00000
#define XPAR_AXI_TIMER_0_HIGHADDR 0x41c03fff
#define XPAR_AXI_TIMER_0_CLOCK_FREQUENCY 0x5f5e100
#define XPAR_AXI_TIMER_0_INTERRUPTS 0x2001
#define XPAR_AXI_TIMER_0_INTERRUPT_PARENT 0x41200001

/* Canonical definitions for peripheral AXI_TIMER_0 */
#define XPAR_XTMRCTR_0_BASEADDR 0x41c00000
#define XPAR_XTMRCTR_0_HIGHADDR 0x41c03fff
#define XPAR_XTMRCTR_0_COMPATIBLE xlnx,axi-timer-2.0
#define XPAR_XTMRCTR_0_CLOCK_FREQUENCY 0x5f5e100
#define XPAR_XTMRCTR_0_INTERRUPTS 0x2001
#define XPAR_XTMRCTR_0_INTERRUPT_PARENT 0x41200001

#define XPAR_XUARTLITE_NUM_INSTANCES 1

/* Definitions for peripheral AXI_UARTLITE_0 */
#define XPAR_AXI_UARTLITE_0_COMPATIBLE xlnx,axi-uartlite-2.0
#define XPAR_AXI_UARTLITE_0_BASEADDR 0x40600000
#define XPAR_AXI_UARTLITE_0_HIGHADDR 0x40603fff
#define XPAR_AXI_UARTLITE_0_BAUDRATE 0x1c200
#define XPAR_AXI_UARTLITE_0_USE_PARITY 0x0
#define XPAR_AXI_UARTLITE_0_ODD_PARITY 0x0
#define XPAR_AXI_UARTLITE_0_DATA_BITS 0x8
#define XPAR_AXI_UARTLITE_0_INTERRUPTS 0x0
#define XPAR_AXI_UARTLITE_0_INTERRUPT_PARENT 0x41200001

/* Canonical definitions for peripheral AXI_UARTLITE_0 */
#define XPAR_XUARTLITE_0_BASEADDR 0x40600000
#define XPAR_XUARTLITE_0_HIGHADDR 0x40603fff
#define XPAR_XUARTLITE_0_BAUDRATE 0x1c200
#define XPAR_XUARTLITE_0_COMPATIBLE xlnx,axi-uartlite-2.0
#define XPAR_XUARTLITE_0_DATA_BITS 0x8
#define XPAR_XUARTLITE_0_INTERRUPTS 0x0
#define XPAR_XUARTLITE_0_INTERRUPT_PARENT 0x41200001
#define XPAR_XUARTLITE_0_ODD_PARITY 0x0
#define XPAR_XUARTLITE_0_USE_PARITY 0x0

/* Definitions for peripheral SERIAL_ADC_PWM_TOP_0 */
#define XPAR_SERIAL_ADC_PWM_TOP_0_BASEADDR 0x10000
#define XPAR_SERIAL_ADC_PWM_TOP_0_HIGHADDR 0x10fff

/* Definitions for peripheral I2S_RECEIVER_0 */
#define XPAR_I2S_RECEIVER_0_BASEADDR 0x44a20000
#define XPAR_I2S_RECEIVER_0_HIGHADDR 0x44a23fff

/*  BOARD definition */
#define XPS_BOARD_TE0725_100_2I

#define XPAR_LMB_BRAM_0_BASEADDRESS 0x0
#define XPAR_LMB_BRAM_0_HIGHADDRESS 0x8000
#define XPAR_CPU_CORE_CLOCK_FREQ_HZ 100000000

#define XPAR_MICROBLAZE_ADDR_SIZE 32

#define STDOUT_BASEADDRESS 0x40600000
#define STDIN_BASEADDRESS 0x40600000

/* Number of SLRs */
#define NUMBER_OF_SLRS 0x1

/* Device ID */
#define XPAR_DEVICE_ID "7a100t"

#endif  /* end of protection macro */