# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.runs/msys_serial_adc_pwm_top_0_1_synth_1/msys_serial_adc_pwm_top_0_1.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "msys_serial_adc_pwm_top_0_1_synth_1" START { ROLLUP_AUTO }
set_param project.vivado.isBlockSynthRun true
OPTRACE "Creating in-memory project" START { }
set_param ips.modRefOverrideMrefDirPath c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/mref
create_project -in_memory -part xc7a100tcsg324-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.cache/wt [current_project]
set_property parent.project_path C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part_repo_paths {C:/Users/kharp/Desktop/test_board/board_files} [current_project]
set_property board_part trenz.biz:te0725_100_2i:part0:1.0 [current_project]
set_property ip_repo_paths {
  c:/Users/kharp/Desktop/soundSteering_halfLUTs/IP
  c:/Users/kharp/Desktop/soundSteering
} [current_project]
update_ip_catalog
set_property ip_output_repo c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_vhdl -library xil_defaultlib {
  C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/new/LUT_64x12.vhd
  C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/backup/_IP/src/adder_17bit.vhd
  C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/backup/_IP/src/compare_match_16.vhd
  C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/backup/_IP/src/compare_match_32.vhd
  C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/backup/_IP/src/counter_16.vhd
  C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/backup/_IP/src/counter_32.vhd
  C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/backup/_IP/src/counter_6.vhd
  C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/backup/_IP/src/flag_register_2bit.vhd
  C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/backup/_IP/src/fullAdder.vhd
  C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/backup/_IP/src/inverter_64bit.vhd
  C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/backup/_IP/src/mux_2to1_16bit.vhd
  C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/backup/_IP/src/mux_4to1_1bit.vhd
  C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/backup/_IP/src/mux_8to1_16bit.vhd
  C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/new/serial_adc_pwm_datapath.vhd
  C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/new/serial_adc_pwm_fsm.vhd
  C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/new/shiftRAM.vhd
  C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/new/shift_left_16.vhd
  C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/kharp/Desktop/shift_right_multiplier_32.vhd
  C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/backup/_IP/src/signed_conversion_16bit.vhd
  C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/new/vhdl_gpio_peripheral.vhd
  C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/backup/_IP/src/vhdl_serial_peripheral.vhd
  C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/new/serial_adc_pwm_top.vhd
}
read_ip -quiet C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/ip/blk_mem_gen_1_1_64/blk_mem_gen_1_1_64.xci
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/ip/blk_mem_gen_1_1_64/blk_mem_gen_1_1_64_ooc.xdc]

read_ip -quiet C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/ip/blk_mem_gen_1_1_63/blk_mem_gen_1_1_63.xci
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/ip/blk_mem_gen_1_1_63/blk_mem_gen_1_1_63_ooc.xdc]

read_ip -quiet C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/ip/blk_mem_gen_1_1_62/blk_mem_gen_1_1_62.xci
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/ip/blk_mem_gen_1_1_62/blk_mem_gen_1_1_62_ooc.xdc]

read_ip -quiet C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/ip/blk_mem_gen_1_1_61/blk_mem_gen_1_1_61.xci
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/ip/blk_mem_gen_1_1_61/blk_mem_gen_1_1_61_ooc.xdc]

read_ip -quiet C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/ip/blk_mem_gen_1_1_60/blk_mem_gen_1_1_60.xci
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/ip/blk_mem_gen_1_1_60/blk_mem_gen_1_1_60_ooc.xdc]

read_ip -quiet C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/ip/blk_mem_gen_1_1_59/blk_mem_gen_1_1_59.xci
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/ip/blk_mem_gen_1_1_59/blk_mem_gen_1_1_59_ooc.xdc]

read_ip -quiet C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/ip/blk_mem_gen_1_1_58/blk_mem_gen_1_1_58.xci
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/ip/blk_mem_gen_1_1_58/blk_mem_gen_1_1_58_ooc.xdc]

read_ip -quiet C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/ip/blk_mem_gen_1_1_57/blk_mem_gen_1_1_57.xci
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/ip/blk_mem_gen_1_1_57/blk_mem_gen_1_1_57_ooc.xdc]

read_ip -quiet C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/ip/blk_mem_gen_1_1_56/blk_mem_gen_1_1_56.xci
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/ip/blk_mem_gen_1_1_56/blk_mem_gen_1_1_56_ooc.xdc]

read_ip -quiet C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/ip/blk_mem_gen_1_1_55/blk_mem_gen_1_1_55.xci
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/ip/blk_mem_gen_1_1_55/blk_mem_gen_1_1_55_ooc.xdc]

read_ip -quiet C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/ip/blk_mem_gen_1_1_54/blk_mem_gen_1_1_54.xci
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/ip/blk_mem_gen_1_1_54/blk_mem_gen_1_1_54_ooc.xdc]

read_ip -quiet C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/ip/blk_mem_gen_1_1_53/blk_mem_gen_1_1_53.xci
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/ip/blk_mem_gen_1_1_53/blk_mem_gen_1_1_53_ooc.xdc]

read_ip -quiet C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/ip/blk_mem_gen_1_1_52/blk_mem_gen_1_1_52.xci
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/ip/blk_mem_gen_1_1_52/blk_mem_gen_1_1_52_ooc.xdc]

read_ip -quiet C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/ip/blk_mem_gen_1_1_51/blk_mem_gen_1_1_51.xci
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/ip/blk_mem_gen_1_1_51/blk_mem_gen_1_1_51_ooc.xdc]

read_ip -quiet C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/ip/blk_mem_gen_1_1_50/blk_mem_gen_1_1_50.xci
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/ip/blk_mem_gen_1_1_50/blk_mem_gen_1_1_50_ooc.xdc]

read_ip -quiet C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/ip/blk_mem_gen_1_1_49/blk_mem_gen_1_1_49.xci
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/ip/blk_mem_gen_1_1_49/blk_mem_gen_1_1_49_ooc.xdc]

read_ip -quiet C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/ip/blk_mem_gen_1_1_48/blk_mem_gen_1_1_48.xci
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/ip/blk_mem_gen_1_1_48/blk_mem_gen_1_1_48_ooc.xdc]

read_ip -quiet C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/ip/blk_mem_gen_1_1_47/blk_mem_gen_1_1_47.xci
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/ip/blk_mem_gen_1_1_47/blk_mem_gen_1_1_47_ooc.xdc]

read_ip -quiet C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/ip/blk_mem_gen_1_1_46/blk_mem_gen_1_1_46.xci
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/ip/blk_mem_gen_1_1_46/blk_mem_gen_1_1_46_ooc.xdc]

read_ip -quiet C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/ip/blk_mem_gen_1_1_45/blk_mem_gen_1_1_45.xci
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/ip/blk_mem_gen_1_1_45/blk_mem_gen_1_1_45_ooc.xdc]

read_ip -quiet C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/ip/blk_mem_gen_1_1_44/blk_mem_gen_1_1_44.xci
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/ip/blk_mem_gen_1_1_44/blk_mem_gen_1_1_44_ooc.xdc]

read_ip -quiet C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/ip/blk_mem_gen_1_1_43/blk_mem_gen_1_1_43.xci
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/ip/blk_mem_gen_1_1_43/blk_mem_gen_1_1_43_ooc.xdc]

read_ip -quiet C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/ip/blk_mem_gen_1_1_42/blk_mem_gen_1_1_42.xci
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/ip/blk_mem_gen_1_1_42/blk_mem_gen_1_1_42_ooc.xdc]

read_ip -quiet C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/ip/blk_mem_gen_1_1_41/blk_mem_gen_1_1_41.xci
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/ip/blk_mem_gen_1_1_41/blk_mem_gen_1_1_41_ooc.xdc]

read_ip -quiet C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/ip/blk_mem_gen_1_1_40/blk_mem_gen_1_1_40.xci
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/ip/blk_mem_gen_1_1_40/blk_mem_gen_1_1_40_ooc.xdc]

read_ip -quiet C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/ip/blk_mem_gen_1_1_39/blk_mem_gen_1_1_39.xci
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/ip/blk_mem_gen_1_1_39/blk_mem_gen_1_1_39_ooc.xdc]

read_ip -quiet C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/ip/blk_mem_gen_1_1_38/blk_mem_gen_1_1_38.xci
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/ip/blk_mem_gen_1_1_38/blk_mem_gen_1_1_38_ooc.xdc]

read_ip -quiet C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/ip/blk_mem_gen_1_1_37/blk_mem_gen_1_1_37.xci
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/ip/blk_mem_gen_1_1_37/blk_mem_gen_1_1_37_ooc.xdc]

read_ip -quiet C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/ip/blk_mem_gen_1_1_36/blk_mem_gen_1_1_36.xci
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/ip/blk_mem_gen_1_1_36/blk_mem_gen_1_1_36_ooc.xdc]

read_ip -quiet C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/ip/blk_mem_gen_1_1_35/blk_mem_gen_1_1_35.xci
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/ip/blk_mem_gen_1_1_35/blk_mem_gen_1_1_35_ooc.xdc]

read_ip -quiet C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/ip/blk_mem_gen_1_1_34/blk_mem_gen_1_1_34.xci
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/ip/blk_mem_gen_1_1_34/blk_mem_gen_1_1_34_ooc.xdc]

read_ip -quiet C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/ip/blk_mem_gen_1_1_33/blk_mem_gen_1_1_33.xci
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/ip/blk_mem_gen_1_1_33/blk_mem_gen_1_1_33_ooc.xdc]

read_ip -quiet C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/ip/blk_mem_gen_1_1_32/blk_mem_gen_1_1_32.xci
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/ip/blk_mem_gen_1_1_32/blk_mem_gen_1_1_32_ooc.xdc]

read_ip -quiet C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/ip/blk_mem_gen_1_1_31/blk_mem_gen_1_1_31.xci
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/ip/blk_mem_gen_1_1_31/blk_mem_gen_1_1_31_ooc.xdc]

read_ip -quiet C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/ip/blk_mem_gen_1_1_30/blk_mem_gen_1_1_30.xci
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/ip/blk_mem_gen_1_1_30/blk_mem_gen_1_1_30_ooc.xdc]

read_ip -quiet C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/ip/blk_mem_gen_1_1_29/blk_mem_gen_1_1_29.xci
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/ip/blk_mem_gen_1_1_29/blk_mem_gen_1_1_29_ooc.xdc]

read_ip -quiet C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/ip/blk_mem_gen_1_1_28/blk_mem_gen_1_1_28.xci
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/ip/blk_mem_gen_1_1_28/blk_mem_gen_1_1_28_ooc.xdc]

read_ip -quiet C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/ip/blk_mem_gen_1_1_27/blk_mem_gen_1_1_27.xci
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/ip/blk_mem_gen_1_1_27/blk_mem_gen_1_1_27_ooc.xdc]

read_ip -quiet C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/ip/blk_mem_gen_1_1_26/blk_mem_gen_1_1_26.xci
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/ip/blk_mem_gen_1_1_26/blk_mem_gen_1_1_26_ooc.xdc]

read_ip -quiet C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/ip/blk_mem_gen_1_1_25/blk_mem_gen_1_1_25.xci
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/ip/blk_mem_gen_1_1_25/blk_mem_gen_1_1_25_ooc.xdc]

read_ip -quiet C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/ip/blk_mem_gen_1_1_24/blk_mem_gen_1_1_24.xci
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/ip/blk_mem_gen_1_1_24/blk_mem_gen_1_1_24_ooc.xdc]

read_ip -quiet C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/ip/blk_mem_gen_1_1_23/blk_mem_gen_1_1_23.xci
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/ip/blk_mem_gen_1_1_23/blk_mem_gen_1_1_23_ooc.xdc]

read_ip -quiet C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/ip/blk_mem_gen_1_1_22/blk_mem_gen_1_1_22.xci
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/ip/blk_mem_gen_1_1_22/blk_mem_gen_1_1_22_ooc.xdc]

read_ip -quiet C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/ip/blk_mem_gen_1_1_21/blk_mem_gen_1_1_21.xci
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/ip/blk_mem_gen_1_1_21/blk_mem_gen_1_1_21_ooc.xdc]

read_ip -quiet C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/ip/blk_mem_gen_1_1_20/blk_mem_gen_1_1_20.xci
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/ip/blk_mem_gen_1_1_20/blk_mem_gen_1_1_20_ooc.xdc]

read_ip -quiet C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/ip/blk_mem_gen_1_1_19/blk_mem_gen_1_1_19.xci
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/ip/blk_mem_gen_1_1_19/blk_mem_gen_1_1_19_ooc.xdc]

read_ip -quiet C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/ip/blk_mem_gen_1_1_18/blk_mem_gen_1_1_18.xci
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/ip/blk_mem_gen_1_1_18/blk_mem_gen_1_1_18_ooc.xdc]

read_ip -quiet C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/ip/blk_mem_gen_1_1_17/blk_mem_gen_1_1_17.xci
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/ip/blk_mem_gen_1_1_17/blk_mem_gen_1_1_17_ooc.xdc]

read_ip -quiet C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/ip/blk_mem_gen_1_1_16/blk_mem_gen_1_1_16.xci
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/ip/blk_mem_gen_1_1_16/blk_mem_gen_1_1_16_ooc.xdc]

read_ip -quiet C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/ip/blk_mem_gen_1_1_15/blk_mem_gen_1_1_15.xci
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/ip/blk_mem_gen_1_1_15/blk_mem_gen_1_1_15_ooc.xdc]

read_ip -quiet C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/ip/blk_mem_gen_1_1_14/blk_mem_gen_1_1_14.xci
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/ip/blk_mem_gen_1_1_14/blk_mem_gen_1_1_14_ooc.xdc]

read_ip -quiet C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/ip/blk_mem_gen_1_1_13/blk_mem_gen_1_1_13.xci
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/ip/blk_mem_gen_1_1_13/blk_mem_gen_1_1_13_ooc.xdc]

read_ip -quiet C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/ip/blk_mem_gen_1_1_12/blk_mem_gen_1_1_12.xci
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/ip/blk_mem_gen_1_1_12/blk_mem_gen_1_1_12_ooc.xdc]

read_ip -quiet C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/ip/blk_mem_gen_1_1_11/blk_mem_gen_1_1_11.xci
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/ip/blk_mem_gen_1_1_11/blk_mem_gen_1_1_11_ooc.xdc]

read_ip -quiet C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/ip/blk_mem_gen_1_1_10/blk_mem_gen_1_1_10.xci
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/ip/blk_mem_gen_1_1_10/blk_mem_gen_1_1_10_ooc.xdc]

read_ip -quiet C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/ip/blk_mem_gen_1_1_9/blk_mem_gen_1_1_9.xci
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/ip/blk_mem_gen_1_1_9/blk_mem_gen_1_1_9_ooc.xdc]

read_ip -quiet C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/ip/blk_mem_gen_1_1_8/blk_mem_gen_1_1_8.xci
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/ip/blk_mem_gen_1_1_8/blk_mem_gen_1_1_8_ooc.xdc]

read_ip -quiet C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/ip/blk_mem_gen_1_1_7/blk_mem_gen_1_1_7.xci
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/ip/blk_mem_gen_1_1_7/blk_mem_gen_1_1_7_ooc.xdc]

read_ip -quiet C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/ip/blk_mem_gen_1_1_6/blk_mem_gen_1_1_6.xci
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/ip/blk_mem_gen_1_1_6/blk_mem_gen_1_1_6_ooc.xdc]

read_ip -quiet C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/ip/blk_mem_gen_1_1_5/blk_mem_gen_1_1_5.xci
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/ip/blk_mem_gen_1_1_5/blk_mem_gen_1_1_5_ooc.xdc]

read_ip -quiet C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/ip/blk_mem_gen_1_1_4/blk_mem_gen_1_1_4.xci
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/ip/blk_mem_gen_1_1_4/blk_mem_gen_1_1_4_ooc.xdc]

read_ip -quiet C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/ip/blk_mem_gen_1_1_3/blk_mem_gen_1_1_3.xci
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/ip/blk_mem_gen_1_1_3/blk_mem_gen_1_1_3_ooc.xdc]

read_ip -quiet C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/ip/blk_mem_gen_1_1_2/blk_mem_gen_1_1_2.xci
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/ip/blk_mem_gen_1_1_2/blk_mem_gen_1_1_2_ooc.xdc]

read_ip -quiet C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/ip/blk_mem_gen_1_1_1/blk_mem_gen_1_1_1.xci
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/ip/blk_mem_gen_1_1_1/blk_mem_gen_1_1_1_ooc.xdc]

read_ip -quiet C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]

read_ip -quiet C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/bd/msys/ip/msys_serial_adc_pwm_top_0_1/msys_serial_adc_pwm_top_0_1.xci
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_serial_adc_pwm_top_0_1/msys_serial_adc_pwm_top_0_1_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top msys_serial_adc_pwm_top_0_1 -part xc7a100tcsg324-2 -incremental_mode off -mode out_of_context
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}

rename_ref -prefix_all msys_serial_adc_pwm_top_0_1_

OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef msys_serial_adc_pwm_top_0_1.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "msys_serial_adc_pwm_top_0_1_synth_1_synth_report_utilization_0" "report_utilization -file msys_serial_adc_pwm_top_0_1_utilization_synth.rpt -pb msys_serial_adc_pwm_top_0_1_utilization_synth.pb"
OPTRACE "synth reports" END { }

if { [catch {
  file copy -force C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.runs/msys_serial_adc_pwm_top_0_1_synth_1/msys_serial_adc_pwm_top_0_1.dcp c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_serial_adc_pwm_top_0_1/msys_serial_adc_pwm_top_0_1.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 status "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_serial_adc_pwm_top_0_1/msys_serial_adc_pwm_top_0_1_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_serial_adc_pwm_top_0_1/msys_serial_adc_pwm_top_0_1_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_serial_adc_pwm_top_0_1/msys_serial_adc_pwm_top_0_1_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_serial_adc_pwm_top_0_1/msys_serial_adc_pwm_top_0_1_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if {[file isdir C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.ip_user_files/ip/msys_serial_adc_pwm_top_0_1]} {
  catch { 
    file copy -force c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_serial_adc_pwm_top_0_1/msys_serial_adc_pwm_top_0_1_stub.v C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.ip_user_files/ip/msys_serial_adc_pwm_top_0_1
  }
}

if {[file isdir C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.ip_user_files/ip/msys_serial_adc_pwm_top_0_1]} {
  catch { 
    file copy -force c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_serial_adc_pwm_top_0_1/msys_serial_adc_pwm_top_0_1_stub.vhdl C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.ip_user_files/ip/msys_serial_adc_pwm_top_0_1
  }
}
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "msys_serial_adc_pwm_top_0_1_synth_1" END { }
