# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.runs/synth_4/msys_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_4" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 6
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a100tcsg324-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.cache/wt [current_project]
set_property parent.project_path C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part_repo_paths {C:/Users/kharp/Desktop/test_board/board_files} [current_project]
set_property board_part trenz.biz:te0725_100_2i:part0:1.0 [current_project]
set_property ip_repo_paths {
  c:/Users/kharp/Desktop/soundSteering_halfLUTs/IP
  c:/Users/kharp/Desktop/soundSteering
} [current_project]
update_ip_catalog
set_property ip_output_repo c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/Desktop/coes/16bit_2sComp_ROM.coe
add_files C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/Desktop/coes/t1_lut.coe
add_files C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/Desktop/coes/t2_lut.coe
add_files C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/Desktop/coes/t64_lut.coe
add_files C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/Desktop/coes/t63_lut.coe
add_files C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/Desktop/coes/t62_lut.coe
add_files C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/Desktop/coes/t61_lut.coe
add_files C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/Desktop/coes/t60_lut.coe
add_files C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/Desktop/coes/t59_lut.coe
add_files C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/Desktop/coes/t58_lut.coe
add_files C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/Desktop/coes/t57_lut.coe
add_files C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/Desktop/coes/t56_lut.coe
add_files C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/Desktop/coes/t55_lut.coe
add_files C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/Desktop/coes/t54_lut.coe
add_files C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/Desktop/coes/t53_lut.coe
add_files C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/Desktop/coes/t52_lut.coe
add_files C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/Desktop/coes/t51_lut.coe
add_files C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/Desktop/coes/t50_lut.coe
add_files C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/Desktop/coes/t49_lut.coe
add_files C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/Desktop/coes/t48_lut.coe
add_files C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/Desktop/coes/t47_lut.coe
add_files C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/Desktop/coes/t46_lut.coe
add_files C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/Desktop/coes/t45_lut.coe
add_files C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/Desktop/coes/t44_lut.coe
add_files C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/Desktop/coes/t43_lut.coe
add_files C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/Desktop/coes/t42_lut.coe
add_files C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/Desktop/coes/t41_lut.coe
add_files C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/Desktop/coes/t40_lut.coe
add_files C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/Desktop/coes/t39_lut.coe
add_files C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/Desktop/coes/t38_lut.coe
add_files C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/Desktop/coes/t37_lut.coe
add_files C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/Desktop/coes/t36_lut.coe
add_files C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/Desktop/coes/t35_lut.coe
add_files C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/Desktop/coes/t34_lut.coe
add_files C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/Desktop/coes/t33_lut.coe
add_files C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/Desktop/coes/t3_lut.coe
add_files C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/Desktop/coes/t4_lut.coe
add_files C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/Desktop/coes/t5_lut.coe
add_files C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/Desktop/coes/t6_lut.coe
add_files C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/Desktop/coes/t7_lut.coe
add_files C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/Desktop/coes/t8_lut.coe
add_files C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/Desktop/coes/t9_lut.coe
add_files C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/Desktop/coes/t10_lut.coe
add_files C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/Desktop/coes/t11_lut.coe
add_files C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/Desktop/coes/t13_lut.coe
add_files C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/Desktop/coes/t12_lut.coe
add_files C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/Desktop/coes/t14_lut.coe
add_files C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/Desktop/coes/t15_lut.coe
add_files C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/Desktop/coes/t16_lut.coe
add_files C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/Desktop/coes/t17_lut.coe
add_files C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/Desktop/coes/t18_lut.coe
add_files C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/Desktop/coes/t19_lut.coe
add_files C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/Desktop/coes/t20_lut.coe
add_files C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/Desktop/coes/t21_lut.coe
add_files C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/Desktop/coes/t22_lut.coe
add_files C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/Desktop/coes/t23_lut.coe
add_files C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/Desktop/coes/t24_lut.coe
add_files C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/Desktop/coes/t25_lut.coe
add_files C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/Desktop/coes/t26_lut.coe
add_files C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/Desktop/coes/t27_lut.coe
add_files C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/Desktop/coes/t28_lut.coe
add_files C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/Desktop/coes/t29_lut.coe
add_files C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/Desktop/coes/t30_lut.coe
add_files C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/Desktop/coes/t31_lut.coe
add_files C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/Desktop/coes/t32_lut.coe
add_files C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/Desktop/soundSteering/fw/soundSteering_fw_04_16/build/soundSteering_fw_04_16.elf
set_property SCOPED_TO_REF msys [get_files -all C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/Desktop/soundSteering/fw/soundSteering_fw_04_16/build/soundSteering_fw_04_16.elf]
set_property SCOPED_TO_CELLS microblaze_0 [get_files -all C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/imports/Desktop/soundSteering/fw/soundSteering_fw_04_16/build/soundSteering_fw_04_16.elf]
add_files {{c:/Users/kharp/Desktop/coes/half luts/t1h_lut.coe}}
add_files {{c:/Users/kharp/Desktop/coes/half luts/t2h_lut.coe}}
add_files {{c:/Users/kharp/Desktop/coes/half luts/t3h_lut.coe}}
add_files {{c:/Users/kharp/Desktop/coes/half luts/t5h_lut.coe}}
add_files {{c:/Users/kharp/Desktop/coes/half luts/t4h_lut.coe}}
add_files {{c:/Users/kharp/Desktop/coes/half luts/t6h_lut.coe}}
add_files {{c:/Users/kharp/Desktop/coes/half luts/t7h_lut.coe}}
add_files {{c:/Users/kharp/Desktop/coes/half luts/t8h_lut.coe}}
add_files {{c:/Users/kharp/Desktop/coes/half luts/t9h_lut.coe}}
add_files {{c:/Users/kharp/Desktop/coes/half luts/t10h_lut.coe}}
add_files {{c:/Users/kharp/Desktop/coes/half luts/t11h_lut.coe}}
add_files {{c:/Users/kharp/Desktop/coes/half luts/t12h_lut.coe}}
add_files {{c:/Users/kharp/Desktop/coes/half luts/t13h_lut.coe}}
add_files {{c:/Users/kharp/Desktop/coes/half luts/t14h_lut.coe}}
add_files {{c:/Users/kharp/Desktop/coes/half luts/t15h_lut.coe}}
add_files {{c:/Users/kharp/Desktop/coes/half luts/t16h_lut.coe}}
add_files {{c:/Users/kharp/Desktop/coes/half luts/t17h_lut.coe}}
add_files {{c:/Users/kharp/Desktop/coes/half luts/t18h_lut.coe}}
add_files {{c:/Users/kharp/Desktop/coes/half luts/t19h_lut.coe}}
add_files {{c:/Users/kharp/Desktop/coes/half luts/t20h_lut.coe}}
add_files {{c:/Users/kharp/Desktop/coes/half luts/t21h_lut.coe}}
add_files {{c:/Users/kharp/Desktop/coes/half luts/t22h_lut.coe}}
add_files {{c:/Users/kharp/Desktop/coes/half luts/t23h_lut.coe}}
add_files {{c:/Users/kharp/Desktop/coes/half luts/t24h_lut.coe}}
add_files {{c:/Users/kharp/Desktop/coes/half luts/t25h_lut.coe}}
add_files {{c:/Users/kharp/Desktop/coes/half luts/t26h_lut.coe}}
add_files {{c:/Users/kharp/Desktop/coes/half luts/t27h_lut.coe}}
add_files {{c:/Users/kharp/Desktop/coes/half luts/t28h_lut.coe}}
add_files {{c:/Users/kharp/Desktop/coes/half luts/t29h_lut.coe}}
add_files {{c:/Users/kharp/Desktop/coes/half luts/t30h_lut.coe}}
add_files {{c:/Users/kharp/Desktop/coes/half luts/t31h_lut.coe}}
add_files {{c:/Users/kharp/Desktop/coes/half luts/t32h_lut.coe}}
add_files {{c:/Users/kharp/Desktop/coes/half luts/t33h_lut.coe}}
add_files {{c:/Users/kharp/Desktop/coes/half luts/t34h_lut.coe}}
add_files {{c:/Users/kharp/Desktop/coes/half luts/t35h_lut.coe}}
add_files {{c:/Users/kharp/Desktop/coes/half luts/t36h_lut.coe}}
add_files {{c:/Users/kharp/Desktop/coes/half luts/t37h_lut.coe}}
add_files {{c:/Users/kharp/Desktop/coes/half luts/t38h_lut.coe}}
add_files {{c:/Users/kharp/Desktop/coes/half luts/t39h_lut.coe}}
add_files {{c:/Users/kharp/Desktop/coes/half luts/t40h_lut.coe}}
add_files {{c:/Users/kharp/Desktop/coes/half luts/t64h_lut.coe}}
add_files {{c:/Users/kharp/Desktop/coes/half luts/t63h_lut.coe}}
add_files {{c:/Users/kharp/Desktop/coes/half luts/t62h_lut.coe}}
add_files {{c:/Users/kharp/Desktop/coes/half luts/t61h_lut.coe}}
add_files {{c:/Users/kharp/Desktop/coes/half luts/t60h_lut.coe}}
add_files {{c:/Users/kharp/Desktop/coes/half luts/t59h_lut.coe}}
add_files {{c:/Users/kharp/Desktop/coes/half luts/t58h_lut.coe}}
add_files {{c:/Users/kharp/Desktop/coes/half luts/t57h_lut.coe}}
add_files {{c:/Users/kharp/Desktop/coes/half luts/t56h_lut.coe}}
add_files {{c:/Users/kharp/Desktop/coes/half luts/t55h_lut.coe}}
add_files {{c:/Users/kharp/Desktop/coes/half luts/t54h_lut.coe}}
add_files {{c:/Users/kharp/Desktop/coes/half luts/t53h_lut.coe}}
add_files {{c:/Users/kharp/Desktop/coes/half luts/t52h_lut.coe}}
add_files {{c:/Users/kharp/Desktop/coes/half luts/t51h_lut.coe}}
add_files {{c:/Users/kharp/Desktop/coes/half luts/t50h_lut.coe}}
add_files {{c:/Users/kharp/Desktop/coes/half luts/t49h_lut.coe}}
add_files {{c:/Users/kharp/Desktop/coes/half luts/t48h_lut.coe}}
add_files {{c:/Users/kharp/Desktop/coes/half luts/t47h_lut.coe}}
add_files {{c:/Users/kharp/Desktop/coes/half luts/t46h_lut.coe}}
add_files {{c:/Users/kharp/Desktop/coes/half luts/t45h_lut.coe}}
add_files {{c:/Users/kharp/Desktop/coes/half luts/t44h_lut.coe}}
add_files {{c:/Users/kharp/Desktop/coes/half luts/t43h_lut.coe}}
add_files {{c:/Users/kharp/Desktop/coes/half luts/t42h_lut.coe}}
add_files {{c:/Users/kharp/Desktop/coes/half luts/t41h_lut.coe}}
read_vhdl -library xil_defaultlib C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/hdl/msys_wrapper.vhd
add_files C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/bd/msys/msys.bd
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_axi_iic_0_0_4/msys_axi_iic_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_axi_iic_0_0_4/msys_axi_iic_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_axi_quad_spi_0_0_4/msys_axi_quad_spi_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_axi_quad_spi_0_0_4/msys_axi_quad_spi_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_axi_quad_spi_0_0_4/msys_axi_quad_spi_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_axi_quad_spi_0_0_4/msys_axi_quad_spi_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_axi_timer_0_0_4/msys_axi_timer_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_axi_timer_0_0_4/msys_axi_timer_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_axi_uartlite_0_0_4/msys_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_axi_uartlite_0_0_4/msys_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_axi_uartlite_0_0_4/msys_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_clk_wiz_0_0_4/msys_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_clk_wiz_0_0_4/msys_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_clk_wiz_0_0_4/msys_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_mdm_1_0_4/msys_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_mdm_1_0_4/msys_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_microblaze_0_0_4/msys_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_microblaze_0_0_4/msys_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_microblaze_0_0_4/msys_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_microblaze_0_axi_intc_0_4/msys_microblaze_0_axi_intc_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_microblaze_0_axi_intc_0_4/msys_microblaze_0_axi_intc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_microblaze_0_axi_intc_0_4/msys_microblaze_0_axi_intc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_xbar_0_4/msys_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_dlmb_bram_if_cntlr_0_4/msys_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_dlmb_v10_0_4/msys_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_ilmb_bram_if_cntlr_0_4/msys_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_ilmb_v10_0_4/msys_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_lmb_bram_0_4/msys_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_rst_clk_wiz_0_100M_0_4/msys_rst_clk_wiz_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_rst_clk_wiz_0_100M_0_4/msys_rst_clk_wiz_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_rst_clk_wiz_0_100M_0_4/msys_rst_clk_wiz_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_axi_quad_spi_1_0_4/msys_axi_quad_spi_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_axi_quad_spi_1_0_4/msys_axi_quad_spi_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_axi_quad_spi_1_0_4/msys_axi_quad_spi_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_axi_quad_spi_1_0_4/msys_axi_quad_spi_1_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_i2s_receiver_0_0_4/msys_i2s_receiver_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_i2s_receiver_0_0_4/msys_i2s_receiver_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_serial_adc_pwm_top_0_1/msys_serial_adc_pwm_top_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/msys_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_microblaze_0_0_4/data/mb_bootloop_le.elf]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/kharp/Desktop/axi_lite_test_cm32/constraints/_i_bitgen_common.xdc
set_property used_in_implementation false [get_files C:/Users/kharp/Desktop/axi_lite_test_cm32/constraints/_i_bitgen_common.xdc]

read_xdc C:/Users/kharp/Desktop/axi_lite_test_cm32/constraints/vivado_target.xdc
set_property used_in_implementation false [get_files C:/Users/kharp/Desktop/axi_lite_test_cm32/constraints/vivado_target.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/utils_1/imports/synth_4/msys_wrapper.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top msys_wrapper -part xc7a100tcsg324-2
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef msys_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_4_synth_report_utilization_0" "report_utilization -file msys_wrapper_utilization_synth.rpt -pb msys_wrapper_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_4" END { }
