set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 66 [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]
set_property BITSTREAM.CONFIG.SPI_32BIT_ADDR YES [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property BITSTREAM.CONFIG.M1PIN PULLNONE [current_design]
set_property BITSTREAM.CONFIG.M2PIN PULLNONE [current_design]
set_property BITSTREAM.CONFIG.M0PIN PULLNONE [current_design]

set_property BITSTREAM.CONFIG.USR_ACCESS TIMESTAMP [current_design]

set_property PACKAGE_PIN A4 [get_ports heartbeat_led]
set_property PACKAGE_PIN D5 [get_ports ext_rst_esp]
set_property PACKAGE_PIN T4 [get_ports pwm_fan]
set_property PACKAGE_PIN P5 [get_ports pwm_buff_en]
set_property IOSTANDARD LVCMOS33 [get_ports pwm_fan]
set_property IOSTANDARD LVCMOS33 [get_ports pwm_buff_en]
set_property IOSTANDARD LVCMOS33 [get_ports ext_rst_esp]
set_property IOSTANDARD LVCMOS33 [get_ports heartbeat_led]

set_property PACKAGE_PIN B3 [get_ports esp32_miso]

set_property PACKAGE_PIN U1 [get_ports {extra_io[0]}]
set_property PACKAGE_PIN U2 [get_ports {extra_io[1]}]
set_property PACKAGE_PIN U3 [get_ports {extra_io[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {extra_io[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {extra_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {extra_io[0]}]


set_property PACKAGE_PIN U4 [get_ports cs]
set_property PACKAGE_PIN T5 [get_ports scl]
set_property PACKAGE_PIN N5 [get_ports sdi]
set_property PACKAGE_PIN V2 [get_ports sdoa]
set_property PACKAGE_PIN V1 [get_ports sdob]
set_property PACKAGE_PIN D4 [get_ports tx_active_led]
set_property IOSTANDARD LVCMOS33 [get_ports tx_active_led]
set_property IOSTANDARD LVCMOS33 [get_ports sdob]
set_property IOSTANDARD LVCMOS33 [get_ports sdoa]
set_property IOSTANDARD LVCMOS33 [get_ports sdi]
set_property IOSTANDARD LVCMOS33 [get_ports scl]
set_property IOSTANDARD LVCMOS33 [get_ports cs]

set_property PACKAGE_PIN B1 [get_ports i2s_scl]
set_property PACKAGE_PIN C1 [get_ports i2s_ws]
set_property PACKAGE_PIN B2 [get_ports i2s_sda]
set_property IOSTANDARD LVCMOS33 [get_ports i2s_scl]
set_property IOSTANDARD LVCMOS33 [get_ports i2s_sda]
set_property IOSTANDARD LVCMOS33 [get_ports i2s_ws]

set_property PACKAGE_PIN A1 [get_ports esp32_mosi]
set_property PACKAGE_PIN C2 [get_ports esp32_sck]
set_property PACKAGE_PIN A3 [get_ports esp32_ss]
set_property IOSTANDARD LVCMOS33 [get_ports esp32_ss]
set_property IOSTANDARD LVCMOS33 [get_ports esp32_sck]
set_property IOSTANDARD LVCMOS33 [get_ports esp32_mosi]
set_property IOSTANDARD LVCMOS33 [get_ports esp32_miso]

set_property PACKAGE_PIN K1 [get_ports {pwm_out[64]}]
set_property PACKAGE_PIN G2 [get_ports {pwm_out[63]}]
set_property PACKAGE_PIN E2 [get_ports {pwm_out[62]}]
set_property PACKAGE_PIN F1 [get_ports {pwm_out[61]}]
set_property PACKAGE_PIN R6 [get_ports {pwm_out[1]}]
set_property PACKAGE_PIN V4 [get_ports {pwm_out[2]}]
set_property PACKAGE_PIN R8 [get_ports {pwm_out[3]}]
set_property PACKAGE_PIN U9 [get_ports {pwm_out[4]}]
set_property PACKAGE_PIN A6 [get_ports {pwm_out[5]}]
set_property PACKAGE_PIN B7 [get_ports {pwm_out[6]}]
set_property PACKAGE_PIN C7 [get_ports {pwm_out[7]}]
set_property PACKAGE_PIN G6 [get_ports {pwm_out[8]}]
set_property PACKAGE_PIN T6 [get_ports {pwm_out[9]}]
set_property PACKAGE_PIN V6 [get_ports {pwm_out[10]}]
set_property PACKAGE_PIN M6 [get_ports {pwm_out[11]}]
set_property PACKAGE_PIN U7 [get_ports {pwm_out[12]}]
set_property PACKAGE_PIN C4 [get_ports {pwm_out[13]}]
set_property PACKAGE_PIN C6 [get_ports {pwm_out[14]}]
set_property PACKAGE_PIN D7 [get_ports {pwm_out[15]}]
set_property PACKAGE_PIN E5 [get_ports {pwm_out[16]}]
set_property PACKAGE_PIN U6 [get_ports {pwm_out[17]}]
set_property PACKAGE_PIN N6 [get_ports {pwm_out[18]}]
set_property PACKAGE_PIN V7 [get_ports {pwm_out[19]}]
set_property PACKAGE_PIN R7 [get_ports {pwm_out[20]}]
set_property PACKAGE_PIN E6 [get_ports {pwm_out[21]}]
set_property PACKAGE_PIN E7 [get_ports {pwm_out[22]}]
set_property PACKAGE_PIN C5 [get_ports {pwm_out[23]}]
set_property PACKAGE_PIN B4 [get_ports {pwm_out[24]}]
set_property PACKAGE_PIN V9 [get_ports {pwm_out[25]}]
set_property PACKAGE_PIN T8 [get_ports {pwm_out[26]}]
set_property PACKAGE_PIN V5 [get_ports {pwm_out[27]}]
set_property PACKAGE_PIN R5 [get_ports {pwm_out[28]}]
set_property PACKAGE_PIN F6 [get_ports {pwm_out[29]}]
set_property PACKAGE_PIN D8 [get_ports {pwm_out[30]}]
set_property PACKAGE_PIN B6 [get_ports {pwm_out[31]}]
set_property PACKAGE_PIN A5 [get_ports {pwm_out[32]}]
set_property PACKAGE_PIN M3 [get_ports {pwm_out[33]}]
set_property PACKAGE_PIN M1 [get_ports {pwm_out[34]}]
set_property PACKAGE_PIN R3 [get_ports {pwm_out[35]}]
set_property PACKAGE_PIN P3 [get_ports {pwm_out[36]}]
set_property PACKAGE_PIN K2 [get_ports {pwm_out[37]}]
set_property PACKAGE_PIN H2 [get_ports {pwm_out[38]}]
set_property PACKAGE_PIN D2 [get_ports {pwm_out[39]}]
set_property PACKAGE_PIN E1 [get_ports {pwm_out[40]}]
set_property PACKAGE_PIN N1 [get_ports {pwm_out[41]}]
set_property PACKAGE_PIN R2 [get_ports {pwm_out[42]}]
set_property PACKAGE_PIN M4 [get_ports {pwm_out[43]}]
set_property PACKAGE_PIN R1 [get_ports {pwm_out[44]}]
set_property PACKAGE_PIN F4 [get_ports {pwm_out[45]}]
set_property PACKAGE_PIN E3 [get_ports {pwm_out[46]}]
set_property PACKAGE_PIN G1 [get_ports {pwm_out[47]}]
set_property PACKAGE_PIN J3 [get_ports {pwm_out[48]}]
set_property PACKAGE_PIN T1 [get_ports {pwm_out[49]}]
set_property PACKAGE_PIN N4 [get_ports {pwm_out[50]}]
set_property PACKAGE_PIN P2 [get_ports {pwm_out[51]}]
set_property PACKAGE_PIN N2 [get_ports {pwm_out[52]}]
set_property PACKAGE_PIN J2 [get_ports {pwm_out[53]}]
set_property PACKAGE_PIN H1 [get_ports {pwm_out[54]}]
set_property PACKAGE_PIN D3 [get_ports {pwm_out[55]}]
set_property PACKAGE_PIN F3 [get_ports {pwm_out[56]}]
set_property PACKAGE_PIN P4 [get_ports {pwm_out[57]}]
set_property PACKAGE_PIN T3 [get_ports {pwm_out[58]}]
set_property PACKAGE_PIN L1 [get_ports {pwm_out[59]}]
set_property PACKAGE_PIN M2 [get_ports {pwm_out[60]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwm_out[64]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwm_out[63]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwm_out[62]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwm_out[61]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwm_out[60]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwm_out[59]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwm_out[58]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwm_out[57]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwm_out[56]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwm_out[55]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwm_out[54]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwm_out[53]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwm_out[52]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwm_out[51]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwm_out[50]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwm_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwm_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwm_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwm_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwm_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwm_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwm_out[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwm_out[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwm_out[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwm_out[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwm_out[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwm_out[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwm_out[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwm_out[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwm_out[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwm_out[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwm_out[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwm_out[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwm_out[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwm_out[21]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwm_out[22]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwm_out[23]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwm_out[24]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwm_out[25]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwm_out[26]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwm_out[27]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwm_out[28]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwm_out[29]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwm_out[30]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwm_out[49]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwm_out[48]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwm_out[47]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwm_out[46]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwm_out[45]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwm_out[44]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwm_out[43]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwm_out[42]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwm_out[41]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwm_out[40]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwm_out[39]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwm_out[38]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwm_out[37]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwm_out[36]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwm_out[35]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwm_out[34]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwm_out[33]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwm_out[32]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwm_out[31]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwm_out[17]}]

