@echo off
REM ****************************************************************************
REM Vivado (TM) v2023.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Thu Apr 25 03:06:24 -0400 2024
REM SW Build 4029153 on Fri Oct 13 20:14:34 MDT 2023
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim test_serial_adc_pwm_top_behav -key {Behavioral:sim_1:Functional:test_serial_adc_pwm_top} -tclbatch test_serial_adc_pwm_top.tcl -view C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sim_1/imports/Desktop/test_board/vivado/signedDecimalRadix.wcfg -view C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sim_1/imports/Desktop/test_board/vivado/topModule_tb_wvfm_cfg.wcfg -view C:/Users/kharp/Desktop/soundSteering_halfLUTs/test_vhdl_serial_peripheral.wcfg -view C:/Users/kharp/Desktop/soundSteering_halfLUTs/test_shiftRAM.wcfg -log simulate.log"
call xsim  test_serial_adc_pwm_top_behav -key {Behavioral:sim_1:Functional:test_serial_adc_pwm_top} -tclbatch test_serial_adc_pwm_top.tcl -view C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sim_1/imports/Desktop/test_board/vivado/signedDecimalRadix.wcfg -view C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sim_1/imports/Desktop/test_board/vivado/topModule_tb_wvfm_cfg.wcfg -view C:/Users/kharp/Desktop/soundSteering_halfLUTs/test_vhdl_serial_peripheral.wcfg -view C:/Users/kharp/Desktop/soundSteering_halfLUTs/test_shiftRAM.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
