# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.runs/msys_soundSteering_axi_li_0_0_synth_1/msys_soundSteering_axi_li_0_0.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "msys_soundSteering_axi_li_0_0_synth_1" START { ROLLUP_AUTO }
set_param project.vivado.isBlockSynthRun true
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a100tcsg324-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.cache/wt [current_project]
set_property parent.project_path C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part_repo_paths {C:/Users/kharp/Desktop/test_board/board_files} [current_project]
set_property board_part trenz.biz:te0725_100_2i:part0:1.0 [current_project]
set_property ip_repo_paths {
  c:/Users/kharp/Desktop/soundSteering_halfLUTs/IP
  c:/Users/kharp/Desktop/soundSteering
} [current_project]
update_ip_catalog
set_property ip_output_repo c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_ip -quiet C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.srcs/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/msys_soundSteering_axi_li_0_0.xci
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/blk_mem_gen_1_1_1/blk_mem_gen_1_1_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/blk_mem_gen_1_1_2/blk_mem_gen_1_1_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/blk_mem_gen_1_1_3/blk_mem_gen_1_1_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/blk_mem_gen_1_1_4/blk_mem_gen_1_1_4_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/blk_mem_gen_1_1_5/blk_mem_gen_1_1_5_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/blk_mem_gen_1_1_6/blk_mem_gen_1_1_6_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/blk_mem_gen_1_1_7/blk_mem_gen_1_1_7_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/blk_mem_gen_1_1_8/blk_mem_gen_1_1_8_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/blk_mem_gen_1_1_9/blk_mem_gen_1_1_9_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/blk_mem_gen_1_1_10/blk_mem_gen_1_1_10_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/blk_mem_gen_1_1_11/blk_mem_gen_1_1_11_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/blk_mem_gen_1_1_12/blk_mem_gen_1_1_12_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/blk_mem_gen_1_1_13/blk_mem_gen_1_1_13_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/blk_mem_gen_1_1_14/blk_mem_gen_1_1_14_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/blk_mem_gen_1_1_15/blk_mem_gen_1_1_15_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/blk_mem_gen_1_1_16/blk_mem_gen_1_1_16_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/blk_mem_gen_1_1_17/blk_mem_gen_1_1_17_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/blk_mem_gen_1_1_18/blk_mem_gen_1_1_18_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/blk_mem_gen_1_1_19/blk_mem_gen_1_1_19_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/blk_mem_gen_1_1_20/blk_mem_gen_1_1_20_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/blk_mem_gen_1_1_21/blk_mem_gen_1_1_21_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/blk_mem_gen_1_1_22/blk_mem_gen_1_1_22_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/blk_mem_gen_1_1_23/blk_mem_gen_1_1_23_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/blk_mem_gen_1_1_24/blk_mem_gen_1_1_24_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/blk_mem_gen_1_1_25/blk_mem_gen_1_1_25_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/blk_mem_gen_1_1_26/blk_mem_gen_1_1_26_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/blk_mem_gen_1_1_27/blk_mem_gen_1_1_27_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/blk_mem_gen_1_1_28/blk_mem_gen_1_1_28_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/blk_mem_gen_1_1_29/blk_mem_gen_1_1_29_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/blk_mem_gen_1_1_30/blk_mem_gen_1_1_30_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/blk_mem_gen_1_1_31/blk_mem_gen_1_1_31_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/blk_mem_gen_1_1_32/blk_mem_gen_1_1_32_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/blk_mem_gen_1_1_33/blk_mem_gen_1_1_33_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/blk_mem_gen_1_1_34/blk_mem_gen_1_1_34_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/blk_mem_gen_1_1_35/blk_mem_gen_1_1_35_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/blk_mem_gen_1_1_36/blk_mem_gen_1_1_36_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/blk_mem_gen_1_1_37/blk_mem_gen_1_1_37_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/blk_mem_gen_1_1_38/blk_mem_gen_1_1_38_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/blk_mem_gen_1_1_39/blk_mem_gen_1_1_39_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/blk_mem_gen_1_1_40/blk_mem_gen_1_1_40_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/blk_mem_gen_1_1_41/blk_mem_gen_1_1_41_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/blk_mem_gen_1_1_42/blk_mem_gen_1_1_42_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/blk_mem_gen_1_1_43/blk_mem_gen_1_1_43_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/blk_mem_gen_1_1_44/blk_mem_gen_1_1_44_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/blk_mem_gen_1_1_45/blk_mem_gen_1_1_45_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/blk_mem_gen_1_1_46/blk_mem_gen_1_1_46_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/blk_mem_gen_1_1_47/blk_mem_gen_1_1_47_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/blk_mem_gen_1_1_48/blk_mem_gen_1_1_48_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/blk_mem_gen_1_1_49/blk_mem_gen_1_1_49_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/blk_mem_gen_1_1_50/blk_mem_gen_1_1_50_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/blk_mem_gen_1_1_51/blk_mem_gen_1_1_51_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/blk_mem_gen_1_1_52/blk_mem_gen_1_1_52_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/blk_mem_gen_1_1_53/blk_mem_gen_1_1_53_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/blk_mem_gen_1_1_54/blk_mem_gen_1_1_54_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/blk_mem_gen_1_1_55/blk_mem_gen_1_1_55_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/blk_mem_gen_1_1_56/blk_mem_gen_1_1_56_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/blk_mem_gen_1_1_57/blk_mem_gen_1_1_57_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/blk_mem_gen_1_1_58/blk_mem_gen_1_1_58_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/blk_mem_gen_1_1_59/blk_mem_gen_1_1_59_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/blk_mem_gen_1_1_60/blk_mem_gen_1_1_60_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/blk_mem_gen_1_1_61/blk_mem_gen_1_1_61_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/blk_mem_gen_1_1_62/blk_mem_gen_1_1_62_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/blk_mem_gen_1_1_63/blk_mem_gen_1_1_63_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/blk_mem_gen_1_1_64/blk_mem_gen_1_1_64_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_soundSteering_axi_0_0/src/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_soundSteering_axi_0_0/src/blk_mem_gen_1_1/blk_mem_gen_1_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_soundSteering_axi_0_0/src/blk_mem_gen_1_2/blk_mem_gen_1_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_soundSteering_axi_0_0/src/blk_mem_gen_1_3/blk_mem_gen_1_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_soundSteering_axi_0_0/src/blk_mem_gen_1_4/blk_mem_gen_1_4_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_soundSteering_axi_0_0/src/blk_mem_gen_1_5/blk_mem_gen_1_5_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_soundSteering_axi_0_0/src/blk_mem_gen_1_6/blk_mem_gen_1_6_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_soundSteering_axi_0_0/src/blk_mem_gen_1_7/blk_mem_gen_1_7_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_soundSteering_axi_0_0/src/blk_mem_gen_1_8/blk_mem_gen_1_8_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_soundSteering_axi_0_0/src/blk_mem_gen_1_9/blk_mem_gen_1_9_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_soundSteering_axi_0_0/src/blk_mem_gen_1_10/blk_mem_gen_1_10_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_soundSteering_axi_0_0/src/blk_mem_gen_1_11/blk_mem_gen_1_11_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_soundSteering_axi_0_0/src/blk_mem_gen_1_12/blk_mem_gen_1_12_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_soundSteering_axi_0_0/src/blk_mem_gen_1_13/blk_mem_gen_1_13_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_soundSteering_axi_0_0/src/blk_mem_gen_1_14/blk_mem_gen_1_14_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_soundSteering_axi_0_0/src/blk_mem_gen_1_15/blk_mem_gen_1_15_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_soundSteering_axi_0_0/src/blk_mem_gen_1_16/blk_mem_gen_1_16_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_soundSteering_axi_0_0/src/blk_mem_gen_1_17/blk_mem_gen_1_17_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_soundSteering_axi_0_0/src/blk_mem_gen_1_18/blk_mem_gen_1_18_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_soundSteering_axi_0_0/src/blk_mem_gen_1_19/blk_mem_gen_1_19_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_soundSteering_axi_0_0/src/blk_mem_gen_1_20/blk_mem_gen_1_20_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_soundSteering_axi_0_0/src/blk_mem_gen_1_21/blk_mem_gen_1_21_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_soundSteering_axi_0_0/src/blk_mem_gen_1_22/blk_mem_gen_1_22_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_soundSteering_axi_0_0/src/blk_mem_gen_1_23/blk_mem_gen_1_23_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_soundSteering_axi_0_0/src/blk_mem_gen_1_24/blk_mem_gen_1_24_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_soundSteering_axi_0_0/src/blk_mem_gen_1_25/blk_mem_gen_1_25_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_soundSteering_axi_0_0/src/blk_mem_gen_1_26/blk_mem_gen_1_26_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_soundSteering_axi_0_0/src/blk_mem_gen_1_27/blk_mem_gen_1_27_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_soundSteering_axi_0_0/src/blk_mem_gen_1_28/blk_mem_gen_1_28_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_soundSteering_axi_0_0/src/blk_mem_gen_1_29/blk_mem_gen_1_29_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_soundSteering_axi_0_0/src/blk_mem_gen_1_30/blk_mem_gen_1_30_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_soundSteering_axi_0_0/src/blk_mem_gen_1_31/blk_mem_gen_1_31_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_soundSteering_axi_0_0/src/blk_mem_gen_1_32/blk_mem_gen_1_32_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_soundSteering_axi_0_0/src/blk_mem_gen_1_33/blk_mem_gen_1_33_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_soundSteering_axi_0_0/src/blk_mem_gen_1_34/blk_mem_gen_1_34_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_soundSteering_axi_0_0/src/blk_mem_gen_1_35/blk_mem_gen_1_35_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_soundSteering_axi_0_0/src/blk_mem_gen_1_36/blk_mem_gen_1_36_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_soundSteering_axi_0_0/src/blk_mem_gen_1_37/blk_mem_gen_1_37_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_soundSteering_axi_0_0/src/blk_mem_gen_1_38/blk_mem_gen_1_38_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_soundSteering_axi_0_0/src/blk_mem_gen_1_39/blk_mem_gen_1_39_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_soundSteering_axi_0_0/src/blk_mem_gen_1_40/blk_mem_gen_1_40_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_soundSteering_axi_0_0/src/blk_mem_gen_1_41/blk_mem_gen_1_41_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_soundSteering_axi_0_0/src/blk_mem_gen_1_42/blk_mem_gen_1_42_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_soundSteering_axi_0_0/src/blk_mem_gen_1_43/blk_mem_gen_1_43_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_soundSteering_axi_0_0/src/blk_mem_gen_1_44/blk_mem_gen_1_44_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_soundSteering_axi_0_0/src/blk_mem_gen_1_45/blk_mem_gen_1_45_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_soundSteering_axi_0_0/src/blk_mem_gen_1_46/blk_mem_gen_1_46_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_soundSteering_axi_0_0/src/blk_mem_gen_1_47/blk_mem_gen_1_47_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_soundSteering_axi_0_0/src/blk_mem_gen_1_48/blk_mem_gen_1_48_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_soundSteering_axi_0_0/src/blk_mem_gen_1_49/blk_mem_gen_1_49_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_soundSteering_axi_0_0/src/blk_mem_gen_1_50/blk_mem_gen_1_50_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_soundSteering_axi_0_0/src/blk_mem_gen_1_51/blk_mem_gen_1_51_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_soundSteering_axi_0_0/src/blk_mem_gen_1_52/blk_mem_gen_1_52_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_soundSteering_axi_0_0/src/blk_mem_gen_1_53/blk_mem_gen_1_53_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_soundSteering_axi_0_0/src/blk_mem_gen_1_54/blk_mem_gen_1_54_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_soundSteering_axi_0_0/src/blk_mem_gen_1_55/blk_mem_gen_1_55_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_soundSteering_axi_0_0/src/blk_mem_gen_1_56/blk_mem_gen_1_56_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_soundSteering_axi_0_0/src/blk_mem_gen_1_57/blk_mem_gen_1_57_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_soundSteering_axi_0_0/src/blk_mem_gen_1_58/blk_mem_gen_1_58_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_soundSteering_axi_0_0/src/blk_mem_gen_1_59/blk_mem_gen_1_59_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_soundSteering_axi_0_0/src/blk_mem_gen_1_60/blk_mem_gen_1_60_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_soundSteering_axi_0_0/src/blk_mem_gen_1_61/blk_mem_gen_1_61_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_soundSteering_axi_0_0/src/blk_mem_gen_1_62/blk_mem_gen_1_62_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_soundSteering_axi_0_0/src/blk_mem_gen_1_63/blk_mem_gen_1_63_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_soundSteering_axi_0_0/src/blk_mem_gen_1_64/blk_mem_gen_1_64_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_soundSteering_axi_0_0/src/_i_bitgen_common.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_soundSteering_axi_0_0/src/_i_bitgen_common.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_soundSteering_axi_0_0/src/vivado_target.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_i2s_receiver_0_0/msys_i2s_receiver_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_axi_quad_spi_1_0/msys_axi_quad_spi_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_axi_quad_spi_1_0/msys_axi_quad_spi_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_axi_quad_spi_1_0/msys_axi_quad_spi_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_axi_quad_spi_1_0/msys_axi_quad_spi_1_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_rst_clk_wiz_0_100M_0/msys_rst_clk_wiz_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_rst_clk_wiz_0_100M_0/msys_rst_clk_wiz_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_lmb_bram_0/msys_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_microblaze_0_axi_intc_0/msys_microblaze_0_axi_intc_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_microblaze_0_axi_intc_0/msys_microblaze_0_axi_intc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_microblaze_0_axi_intc_0/msys_microblaze_0_axi_intc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_microblaze_0_0/msys_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_microblaze_0_0/msys_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_mdm_1_0/msys_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_mdm_1_0/msys_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_clk_wiz_0_0/msys_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_clk_wiz_0_0/msys_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_clk_wiz_0_0/msys_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_axi_uartlite_0_0/msys_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_axi_uartlite_0_0/msys_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_axi_uartlite_0_0/msys_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_axi_timer_0_0/msys_axi_timer_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_axi_timer_0_0/msys_axi_timer_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_axi_quad_spi_0_0/msys_axi_quad_spi_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_axi_quad_spi_0_0/msys_axi_quad_spi_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_axi_quad_spi_0_0/msys_axi_quad_spi_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_axi_quad_spi_0_0/msys_axi_quad_spi_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_axi_iic_0_0/msys_axi_iic_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/msys_axi_iic_0_0/msys_axi_iic_0_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/_i_bitgen_common.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/_i_bitgen_common.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/src/vivado_target.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
OPTRACE "Configure IP Cache" START { }

set cacheID [config_ip_cache -export -no_bom  -dir C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.runs/msys_soundSteering_axi_li_0_0_synth_1 -new_name msys_soundSteering_axi_li_0_0 -ip [get_ips msys_soundSteering_axi_li_0_0]]

OPTRACE "Configure IP Cache" END { }
if { $cacheID == "" } {
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top msys_soundSteering_axi_li_0_0 -part xc7a100tcsg324-2 -incremental_mode off -mode out_of_context
OPTRACE "synth_design" END { }
OPTRACE "Write IP Cache" START { }

#---------------------------------------------------------
# Generate Checkpoint/Stub/Simulation Files For IP Cache
#---------------------------------------------------------
# disable binary constraint mode for IPCache checkpoints
set_param constraints.enableBinaryConstraints false

catch {
 write_checkpoint -force -noxdef -rename_prefix msys_soundSteering_axi_li_0_0_ msys_soundSteering_axi_li_0_0.dcp

 set ipCachedFiles {}
 write_verilog -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ msys_soundSteering_axi_li_0_0_stub.v
 lappend ipCachedFiles msys_soundSteering_axi_li_0_0_stub.v

 write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ msys_soundSteering_axi_li_0_0_stub.vhdl
 lappend ipCachedFiles msys_soundSteering_axi_li_0_0_stub.vhdl

 write_verilog -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ msys_soundSteering_axi_li_0_0_sim_netlist.v
 lappend ipCachedFiles msys_soundSteering_axi_li_0_0_sim_netlist.v

 write_vhdl -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ msys_soundSteering_axi_li_0_0_sim_netlist.vhdl
 lappend ipCachedFiles msys_soundSteering_axi_li_0_0_sim_netlist.vhdl
 set TIME_taken [expr [clock seconds] - $TIME_start]

 if { [get_msg_config -count -severity {CRITICAL WARNING}] == 0 } {
  config_ip_cache -add -dcp msys_soundSteering_axi_li_0_0.dcp -move_files $ipCachedFiles   -synth_runtime $TIME_taken  -ip [get_ips msys_soundSteering_axi_li_0_0]
 }
OPTRACE "Write IP Cache" END { }
}
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}

rename_ref -prefix_all msys_soundSteering_axi_li_0_0_

OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef msys_soundSteering_axi_li_0_0.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "msys_soundSteering_axi_li_0_0_synth_1_synth_report_utilization_0" "report_utilization -file msys_soundSteering_axi_li_0_0_utilization_synth.rpt -pb msys_soundSteering_axi_li_0_0_utilization_synth.pb"
OPTRACE "synth reports" END { }

if { [catch {
  file copy -force C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.runs/msys_soundSteering_axi_li_0_0_synth_1/msys_soundSteering_axi_li_0_0.dcp c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/msys_soundSteering_axi_li_0_0.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 status "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/msys_soundSteering_axi_li_0_0_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/msys_soundSteering_axi_li_0_0_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/msys_soundSteering_axi_li_0_0_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/msys_soundSteering_axi_li_0_0_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}


} else {


if { [catch {
  file copy -force C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.runs/msys_soundSteering_axi_li_0_0_synth_1/msys_soundSteering_axi_li_0_0.dcp c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/msys_soundSteering_axi_li_0_0.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 status "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  file rename -force C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.runs/msys_soundSteering_axi_li_0_0_synth_1/msys_soundSteering_axi_li_0_0_stub.v c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/msys_soundSteering_axi_li_0_0_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.runs/msys_soundSteering_axi_li_0_0_synth_1/msys_soundSteering_axi_li_0_0_stub.vhdl c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/msys_soundSteering_axi_li_0_0_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.runs/msys_soundSteering_axi_li_0_0_synth_1/msys_soundSteering_axi_li_0_0_sim_netlist.v c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/msys_soundSteering_axi_li_0_0_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  file rename -force C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.runs/msys_soundSteering_axi_li_0_0_synth_1/msys_soundSteering_axi_li_0_0_sim_netlist.vhdl c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/msys_soundSteering_axi_li_0_0_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

close [open .end.used_ip_cache.rst w]
}; # end if cacheID 

if {[file isdir C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.ip_user_files/ip/msys_soundSteering_axi_li_0_0]} {
  catch { 
    file copy -force c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/msys_soundSteering_axi_li_0_0_stub.v C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.ip_user_files/ip/msys_soundSteering_axi_li_0_0
  }
}

if {[file isdir C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.ip_user_files/ip/msys_soundSteering_axi_li_0_0]} {
  catch { 
    file copy -force c:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.gen/sources_1/bd/msys/ip/msys_soundSteering_axi_li_0_0/msys_soundSteering_axi_li_0_0_stub.vhdl C:/Users/kharp/Desktop/soundSteering_halfLUTs/soundSteering_halfLUTs.ip_user_files/ip/msys_soundSteering_axi_li_0_0
  }
}
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "msys_soundSteering_axi_li_0_0_synth_1" END { }
